<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Newtonsoft.Json" />
      <PackageReference Include="System.Management" />
    </ItemGroup>

    <ItemGroup>
      <None Update="Tensors\Extensions\TrigonometryExtensions.tt">
        <Generator>TextTemplatingFileGenerator</Generator>
        <LastGenOutput>TrigonometryExtensions.cs</LastGenOutput>
      </None>
    </ItemGroup>

    <ItemGroup>
      <Compile Update="Tensors\Extensions\TrigonometryExtensions.cs">
        <DependentUpon>TrigonometryExtensions.tt</DependentUpon>
      </Compile>
    </ItemGroup>

</Project>
