<Project>
    <ItemGroup Condition="'$(TestProject)' != 'true'">
        <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
            <_Parameter1>$(AssemblyName).UnitTests</_Parameter1>
        </AssemblyAttribute>
    </ItemGroup>
    <ItemGroup Condition="'$(BenchmarkProject)' != 'true'">
        <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
            <_Parameter1>Sci.NET.Benchmarks</_Parameter1>
        </AssemblyAttribute>
    </ItemGroup>
</Project>
