<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Sci.NET.Mathematics\Sci.NET.Mathematics.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <None Update="Tensors\LinearAlgebra\Examples\Contract_[[1]_[0]]_1.safetensors">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="Tensors\LinearAlgebra\Examples\Contract_[[1]_[0]]_2.safetensors">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="Tensors\LinearAlgebra\Examples\matmul_1.safetensors">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="Tensors\LinearAlgebra\Examples\matmul_2.safetensors">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="Tensors\LinearAlgebra\Examples\matmul_3.safetensors">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="Tensors\LinearAlgebra\Examples\matmul_4.safetensors">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="Tensors\LinearAlgebra\Examples\matmul_5.safetensors">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="Tensors\LinearAlgebra\Examples\MatrixMultiply_1.safetensors">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="Tensors\LinearAlgebra\Examples\MatrixMultiply_2.safetensors">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="Tensors\LinearAlgebra\Examples\MatrixMultiply_3.safetensors">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="Tensors\LinearAlgebra\Examples\MatrixMultiply_4.safetensors">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="Tensors\Arithmetic\Examples\Add_1.safetensors">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="Tensors\Arithmetic\Examples\Add_2.safetensors">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="Tensors\Arithmetic\Examples\Add_3.safetensors">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="Tensors\Arithmetic\Examples\Multiply_1.safetensors">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="Tensors\Arithmetic\Examples\Multiply_2.safetensors">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="Tensors\Arithmetic\Examples\Multiply_3.safetensors">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="Tensors\Arithmetic\Examples\Subtract_1.safetensors">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="Tensors\Arithmetic\Examples\Subtract_2.safetensors">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="Tensors\Arithmetic\Examples\Subtract_3.safetensors">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="Tensors\Differentiation\TrigonometryBackwardsTests.tt">
          <Generator>TextTemplatingFileGenerator</Generator>
          <LastGenOutput>TrigonometryBackwardsTests.cs</LastGenOutput>
        </None>
        <None Update="Tensors\Differentiation\ActivationFunctionBackwardsTests.tt">
          <Generator>TextTemplatingFileGenerator</Generator>
          <LastGenOutput>ActivationFunctionBackwardsTests.cs</LastGenOutput>
        </None>
        <None Update="Tensors\Trigonometry\TrigWithBackwardsShould.tt">
          <Generator>TextTemplatingFileGenerator</Generator>
          <LastGenOutput>TrigWithBackwardsShould.cs</LastGenOutput>
        </None>
        <None Update="Tensors\Equality\PointwiseEqualsShould.tt">
          <Generator>TextTemplatingFileGenerator</Generator>
          <LastGenOutput>PointwiseEqualsShould.cs</LastGenOutput>
        </None>
        <None Update="Tensors\Equality\PointwiseGreaterThanOrEqualShould.tt">
          <Generator>TextTemplatingFileGenerator</Generator>
          <LastGenOutput>PointwiseGreaterThanOrEqualShould.cs</LastGenOutput>
        </None>
        <None Update="Tensors\Equality\PointwiseGreaterThanShould.tt">
          <Generator>TextTemplatingFileGenerator</Generator>
          <LastGenOutput>PointwiseGreaterThanShould.cs</LastGenOutput>
        </None>
        <None Update="Tensors\Equality\PointwiseLessThanOrEqualShould.tt">
          <Generator>TextTemplatingFileGenerator</Generator>
          <LastGenOutput>PointwiseLessThanOrEqualShould.cs</LastGenOutput>
        </None>
        <None Update="Tensors\Equality\PointwiseLessThanShould.tt">
          <Generator>TextTemplatingFileGenerator</Generator>
          <LastGenOutput>PointwiseLessThanShould.cs</LastGenOutput>
        </None>
        <None Update="Tensors\Equality\PointwiseNotEqualsShould.tt">
          <Generator>TextTemplatingFileGenerator</Generator>
          <LastGenOutput>PointwiseNotEqualsShould.cs</LastGenOutput>
        </None>
    </ItemGroup>
    <ItemGroup>
        <Folder Include="TestFramework\"/>
    </ItemGroup>
    <ItemGroup>
      <Compile Update="Tensors\Differentiation\TrigonometryBackwardsTests.cs">
        <DependentUpon>TrigonometryBackwardsTests.tt</DependentUpon>
      </Compile>
      <Compile Update="Tensors\Differentiation\ActivationFunctionBackwardsTests.cs">
        <DependentUpon>ActivationFunctionBackwardsTests.tt</DependentUpon>
      </Compile>
      <Compile Update="Tensors\Trigonometry\TrigWithBackwardsShould.cs">
        <DependentUpon>TrigWithBackwardsShould.tt</DependentUpon>
      </Compile>
      <Compile Update="Tensors\Equality\PointwiseEqualsShould.cs">
        <DependentUpon>PointwiseEqualsShould.tt</DependentUpon>
      </Compile>
      <Compile Update="Tensors\Equality\PointwiseGreaterThanOrEqualShould.cs">
        <DependentUpon>PointwiseGreaterThanOrEqualShould.tt</DependentUpon>
      </Compile>
      <Compile Update="Tensors\Equality\PointwiseGreaterThanShould.cs">
        <DependentUpon>PointwiseGreaterThanShould.tt</DependentUpon>
      </Compile>
      <Compile Update="Tensors\Equality\PointwiseLessThanOrEqualShould.cs">
        <DependentUpon>PointwiseLessThanOrEqualShould.tt</DependentUpon>
      </Compile>
      <Compile Update="Tensors\Equality\PointwiseLessThanShould.cs">
        <DependentUpon>PointwiseLessThanShould.tt</DependentUpon>
      </Compile>
      <Compile Update="Tensors\Equality\PointwiseNotEqualsShould.cs">
        <DependentUpon>PointwiseNotEqualsShould.tt</DependentUpon>
      </Compile>
    </ItemGroup>
</Project>
